
CREATE TABLE `user` (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL (email), is_enabled TINYINT(1) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;


CREATE TABLE allergen (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE category (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE recipe (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, category_id INT NOT NULL, INDEX IDX_DA88B13712469DE2 (category_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE recipe_allergen (recipe_id INT NOT NULL, allergen_id INT NOT NULL, INDEX IDX_532FAD5059D8A214 (recipe_id), INDEX IDX_532FAD506E775A4A (allergen_id), PRIMARY KEY (recipe_id, allergen_id)) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE recipe_illustration (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, alt_text VARCHAR(255) DEFAULT NULL, recipe_id INT DEFAULT NULL, INDEX IDX_9C70CD4D59D8A214 (recipe_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE menu (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, nb_person_min INT NOT NULL, price_per_person INT NOT NULL, description LONGTEXT NOT NULL, illustration VARCHAR(255) DEFAULT NULL, text_alt VARCHAR(255) DEFAULT NULL, stock INT DEFAULT NULL, theme_id INT NOT NULL, INDEX IDX_7D053A9359027487 (theme_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE menu_dietetary (menu_id INT NOT NULL, dietetary_id INT NOT NULL, INDEX IDX_B015883ACCD7E912 (menu_id), INDEX IDX_B015883AAE38A2CB (dietetary_id), PRIMARY KEY (menu_id, dietetary_id)) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE menu_recipe (menu_id INT NOT NULL, recipe_id INT NOT NULL, INDEX IDX_9CFE9EFCCD7E912 (menu_id), INDEX IDX_9CFE9EF59D8A214 (recipe_id), PRIMARY KEY (menu_id, recipe_id)) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE theme (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE dietetary (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE review (id INT AUTO_INCREMENT NOT NULL, customer_name VARCHAR(255) NOT NULL, rating INT NOT NULL, comment LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, is_validated TINYINT(1) NOT NULL, order_ref_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_794381C68D9F6D38 (order_ref_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE address (id INT AUTO_INCREMENT NOT NULL, label VARCHAR(255) DEFAULT NULL, street VARCHAR(255) NOT NULL, city VARCHAR(255) NOT NULL, postal_code VARCHAR(255) NOT NULL, phone VARCHAR(255) NOT NULL, is_default TINYINT(1) NOT NULL DEFAULT 0, user_id INT NOT NULL, INDEX IDX_D4E6F81A76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE `order` (id INT AUTO_INCREMENT NOT NULL, order_number VARCHAR(255) NOT NULL, customer_firstname VARCHAR(255) NOT NULL, customer_lastname VARCHAR(255) NOT NULL, customer_email VARCHAR(255) NOT NULL, customer_phone VARCHAR(255) NOT NULL, delivery_address VARCHAR(255) NOT NULL, delivery_date_time DATETIME NOT NULL, delivery_distance_km INT DEFAULT NULL, delivery_cost INT NOT NULL, menu_name VARCHAR(255) NOT NULL, menu_price_per_person INT NOT NULL, number_of_persons INT NOT NULL, menu_subtotal INT NOT NULL, discount_amount INT DEFAULT NULL, total_price INT NOT NULL, status VARCHAR(255) NOT NULL, status_history JSON NOT NULL, has_material_loan TINYINT(1) NOT NULL, material_return_deadline DATETIME DEFAULT NULL, material_returned TINYINT(1) DEFAULT NULL, cancellation_reason LONGTEXT DEFAULT NULL, cancelled_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, accepted_at DATETIME DEFAULT NULL, completed_at DATETIME DEFAULT NULL, user_id INT NOT NULL, review_id INT DEFAULT NULL, INDEX IDX_F5299398A76ED395 (user_id), UNIQUE INDEX UNIQ_F52993983E2E969B (review_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;

-- Table pour la gestion asynchrone des mails.
-- CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL, available_at DATETIME NOT NULL, delivered_at DATETIME DEFAULT NULL, INDEX IDX_75EA56E0FB7336F0 (queue_name), INDEX IDX_75EA56E0E3BD61CE (available_at), INDEX IDX_75EA56E016BA31DB (delivered_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;




ALTER TABLE recipe ADD CONSTRAINT FK_DA88B13712469DE2 FOREIGN KEY (category_id) REFERENCES category (id);

ALTER TABLE recipe_allergen ADD CONSTRAINT FK_532FAD5059D8A214 FOREIGN KEY (recipe_id) REFERENCES recipe (id) ON DELETE CASCADE;

ALTER TABLE recipe_allergen ADD CONSTRAINT FK_532FAD506E775A4A FOREIGN KEY (allergen_id) REFERENCES allergen (id) ON DELETE CASCADE;

ALTER TABLE recipe_illustration ADD CONSTRAINT FK_9C70CD4D59D8A214 FOREIGN KEY (recipe_id) REFERENCES recipe (id);

ALTER TABLE menu ADD CONSTRAINT FK_7D053A9359027487 FOREIGN KEY (theme_id) REFERENCES theme (id);

ALTER TABLE menu_dietetary ADD CONSTRAINT FK_B015883ACCD7E912 FOREIGN KEY (menu_id) REFERENCES menu (id) ON DELETE CASCADE;

ALTER TABLE menu_dietetary ADD CONSTRAINT FK_B015883AAE38A2CB FOREIGN KEY (dietetary_id) REFERENCES dietetary (id) ON DELETE CASCADE;

ALTER TABLE menu_recipe ADD CONSTRAINT FK_9CFE9EFCCD7E912 FOREIGN KEY (menu_id) REFERENCES menu (id) ON DELETE CASCADE;

ALTER TABLE menu_recipe ADD CONSTRAINT FK_9CFE9EF59D8A214 FOREIGN KEY (recipe_id) REFERENCES recipe (id) ON DELETE CASCADE;

ALTER TABLE review ADD CONSTRAINT FK_794381C68D9F6D38 FOREIGN KEY (order_ref_id) REFERENCES `order` (id);

ALTER TABLE address ADD CONSTRAINT FK_D4E6F81A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id);

ALTER TABLE `order` ADD CONSTRAINT FK_F5299398A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id);

ALTER TABLE `order` ADD CONSTRAINT FK_F52993983E2E969B FOREIGN KEY (review_id) REFERENCES review (id);