<?php

namespace App\Tests\Controller;

use App\Entity\Review;
use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

/**
 * Tests fonctionnels du contrôleur Review
 */
class ReviewControllerTest extends WebTestCase
{
    private $client;
    private $entityManager;
    private ?User $testUser = null;

    protected function setUp(): void
    {
        $this->client = static::createClient();
        $this->entityManager = $this->client->getContainer()
            ->get('doctrine')
            ->getManager();

        // Créer un utilisateur de test
        $this->createTestUser();
    }

    protected function tearDown(): void
    {
        // Nettoyer les avis de test
        $reviewRepository = $this->entityManager->getRepository(Review::class);
        $reviews = $reviewRepository->findAll();
        foreach ($reviews as $review) {
            if (str_starts_with($review->getCustomerName(), 'Test')) {
                $this->entityManager->remove($review);
            }
        }
        $this->entityManager->flush();

        parent::tearDown();
        $this->entityManager->close();
        $this->entityManager = null;
    }

    private function createTestUser(): void
    {
        $userRepository = $this->entityManager->getRepository(User::class);
        $this->testUser = $userRepository->findOneBy(['email' => 'test@review.com']);

        if (!$this->testUser) {
            $this->testUser = new User();
            $this->testUser->setEmail('test@review.com');
            $this->testUser->setFirstname('TestFirstname');
            $this->testUser->setLastname('TestLastname');
            $this->testUser->setRoles(['ROLE_USER']);
            $this->testUser->setPassword('password');

            $this->entityManager->persist($this->testUser);
            $this->entityManager->flush();
        }
    }

    public function testReviewIndexPageIsAccessible(): void
    {
        $this->client->request('GET', '/avis');

        $this->assertResponseIsSuccessful();
        $this->assertSelectorTextContains('h1', 'Avis de nos clients');
    }

    public function testNewReviewPageRequiresAuthentication(): void
    {
        $this->client->request('GET', '/avis/nouveau');
        $this->assertResponseRedirects('/connexion');
    }

    public function testNewReviewPageIsAccessibleForAuthenticatedUser(): void
    {
        $this->client->loginUser($this->testUser);
        $this->client->request('GET', '/avis/nouveau');

        $this->assertResponseIsSuccessful();
        $this->assertSelectorExists('form');
        $this->assertSelectorExists('input[name="review[rating]"]');
        $this->assertSelectorExists('textarea[name="review[comment]"]');
    }

    public function testNewReviewFormContainsCorrectFields(): void
    {
        $this->client->loginUser($this->testUser);
        $this->client->request('GET', '/avis/nouveau');

        // Vérifier que le formulaire contient tous les champs nécessaires
        $this->assertSelectorExists('input[name="review[rating]"]');
        $this->assertSelectorExists('textarea[name="review[comment]"]');

        // Vérifier qu'il n'y a PAS de champ customerName (auto-généré)
        $this->assertSelectorNotExists('input[name="review[customerName]"]');
    }

    public function testSubmitValidReview(): void
    {
        $this->client->loginUser($this->testUser);
        $crawler = $this->client->request('GET', '/avis/nouveau');

        $form = $crawler->selectButton('Envoyer mon avis')->form([
            'review[rating]' => '5',
            'review[comment]' => 'Excellent traiteur, je recommande vivement !',
        ]);

        $this->client->submit($form);

        // Vérifier la redirection vers la page compte
        $this->assertResponseRedirects('/compte');

        // Suivre la redirection
        $crawler = $this->client->followRedirect();

        // Vérifier le message flash
        $this->assertSelectorTextContains('.alert-success', 'Merci pour votre avis');
    }

    public function testReviewIsNotValidatedByDefault(): void
    {
        $this->client->loginUser($this->testUser);
        $crawler = $this->client->request('GET', '/avis/nouveau');

        $form = $crawler->selectButton('Envoyer mon avis')->form([
            'review[rating]' => '4',
            'review[comment]' => 'Très bon service',
        ]);

        $this->client->submit($form);

        // Récupérer l'avis créé
        $reviewRepository = $this->entityManager->getRepository(Review::class);
        $review = $reviewRepository->findOneBy(['customerName' => 'TestFirstname T.']);

        $this->assertNotNull($review);
        $this->assertFalse($review->isValidated());
    }

    public function testCustomerNameIsAutoGenerated(): void
    {
        $this->client->loginUser($this->testUser);
        $crawler = $this->client->request('GET', '/avis/nouveau');

        $form = $crawler->selectButton('Envoyer mon avis')->form([
            'review[rating]' => '5',
            'review[comment]' => 'Super expérience !',
        ]);

        $this->client->submit($form);

        // Récupérer l'avis créé
        $reviewRepository = $this->entityManager->getRepository(Review::class);
        $review = $reviewRepository->findOneBy(['comment' => 'Super expérience !']);

        $this->assertNotNull($review);
        // Vérifier le format: Prénom + Initiale
        $this->assertEquals('TestFirstname T.', $review->getCustomerName());
    }

    public function testSubmitReviewWithoutComment(): void
    {
        $this->client->loginUser($this->testUser);
        $crawler = $this->client->request('GET', '/avis/nouveau');

        $form = $crawler->selectButton('Envoyer mon avis')->form([
            'review[rating]' => '5',
            'review[comment]' => '',
        ]);

        $this->client->submit($form);

        // Doit être accepté car le commentaire est optionnel
        $this->assertResponseRedirects('/compte');
    }

    public function testSubmitReviewWithInvalidRating(): void
    {
        $this->client->loginUser($this->testUser);
        $crawler = $this->client->request('GET', '/avis/nouveau');

        // Essayer de soumettre sans sélectionner de note
        $form = $crawler->selectButton('Envoyer mon avis')->form([
            'review[comment]' => 'Commentaire sans note',
        ]);

        $this->client->submit($form);

        // Doit rester sur la page du formulaire avec une erreur
        $this->assertResponseIsUnprocessable();
    }

    public function testReviewCreatedAtIsSetAutomatically(): void
    {
        $this->client->loginUser($this->testUser);
        $crawler = $this->client->request('GET', '/avis/nouveau');

        $form = $crawler->selectButton('Envoyer mon avis')->form([
            'review[rating]' => '4',
            'review[comment]' => 'Test date creation',
        ]);

        $beforeSubmit = new \DateTimeImmutable('-1 second');
        $this->client->submit($form);
        $afterSubmit = new \DateTimeImmutable('+1 second');

        // Récupérer l'avis créé
        $reviewRepository = $this->entityManager->getRepository(Review::class);
        $review = $reviewRepository->findOneBy(['comment' => 'Test date creation']);

        $this->assertNotNull($review);
        $this->assertNotNull($review->getCreatedAt());

        // Vérifier que la date est dans une plage raisonnable (avant -1s et après +1s)
        $this->assertGreaterThanOrEqual($beforeSubmit, $review->getCreatedAt());
        $this->assertLessThanOrEqual($afterSubmit, $review->getCreatedAt());
    }

    public function testMultipleReviewsFromSameUser(): void
    {
        $this->client->loginUser($this->testUser);

        // Soumettre premier avis
        $crawler = $this->client->request('GET', '/avis/nouveau');
        $form = $crawler->selectButton('Envoyer mon avis')->form([
            'review[rating]' => '5',
            'review[comment]' => 'Premier avis',
        ]);
        $this->client->submit($form);

        // Soumettre deuxième avis
        $crawler = $this->client->request('GET', '/avis/nouveau');
        $form = $crawler->selectButton('Envoyer mon avis')->form([
            'review[rating]' => '4',
            'review[comment]' => 'Deuxième avis',
        ]);
        $this->client->submit($form);

        // Vérifier que les deux avis existent
        $reviewRepository = $this->entityManager->getRepository(Review::class);
        $reviews = $reviewRepository->findBy(['customerName' => 'TestFirstname T.']);

        $this->assertGreaterThanOrEqual(2, count($reviews));
    }
}